---
- name: install flatpak
  become: true
  package:
    state: present
    name: flatpak

- name: delete the system flathub remote
  become: true
  flatpak_remote:
    state: absent
    name: flathub

- name: set up the user flathub remote
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
