---
- name: install zsh
  become: true
  package:
    state: present
    name: zsh

- name: set up the zsh config repository
  include_role:
    name: git_repository_setup
  vars:
    repository: zsh

- name: set up zsh for both users
  loop:
    - { user: root,                     home: /root,                    become: true }
    - { user: "{{ ansible_env.USER }}", home: "{{ ansible_env.HOME }}", become: false }
  include_tasks: user_setup.yml
  args:
    apply:
      become: "{{ item.become }}"
