---
- name: gather package facts
  package_facts:

- name: clone the {{ package_name }} aur repository
  when: package_name not in ansible_facts.packages
  git:
    repo: "{{ package_url }}"
    dest: "{{ ansible_env.HOME }}/git/aur/{{ package_name }}"

- name: install {{ package_name }}
  when: package_name not in ansible_facts.packages
  command: makepkg --syncdeps --install --noconfirm
  args:
    chdir: "{{ ansible_env.HOME }}/git/aur/{{ package_name }}"
