---
- name: provision the PC
  hosts: all
  pre_tasks:
    - name: merge common vars with host-specific ones
      loop: "{{ common | merge_dicts(host) | dict2items }}"
      set_fact:
        "{{ item.key }}": "{{ item.value }}"
      tags: always
  roles:
    # establish connection to the internet, enable the firewall and establish ssh connection to the home server
    - role: network
      tags: network

    # install all of the required packages from various sources
    - role: packages
      tags: packages

    # clone personal git repositories from the home server & configure them
    - role: git-repos
      tags: git-repos

    # set up any required configuration files
    - role: config
      tags: config

    # set up file sync from the home server
    - role: file-sync
      tags: file-sync

    # configure and enable any necessary services
    - role: services
      tags: services
