---
# wifi connection
- name: get the wifi interface name
  set_fact:
    wifi_interface: >-
      {{ ansible_facts.interfaces |
        select('match', '^w') |
        list |
        first }}
- name: create the home wifi connection
  nmcli:
    state: present
    conn_name: home
    ifname: "{{ wifi_interface }}"
    type: wifi
    ssid: "{{ secrets.home_wifi.ssid }}"
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ secrets.home_wifi.psk }}"
- name: bring up the home wifi connection
  nmcli:
    state: up
    conn_name: home
- name: wait for internet access
  wait_for:
    host: 1.1.1.1
    port: 53
    timeout: 30

- name: update pacman cache
  become: true
  pacman:
    update_cache: true

- name: install network packages
  become: true
  package:
    state: present
    name:
    - ufw
    - openssh
    - sshpass

# firewall
- name: enable ufw
  become: true
  ufw:
    state: enabled
    default: deny

- name: create the user ssh key
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: true
    ssh_key_type: ed25519

# home server
- name: add a host entry for the home server
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: ^.*\s{{ secrets.home_server.hostname }}$
    line: "{{ secrets.home_server.ip }} {{ secrets.home_server.hostname }}"
- name: add the user ssh key to home server authorized keys
  delegate_to: home_server
  copy:
    src: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
    dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
