---
- name: check pc internet access
  when: inventory_hostname == "pc"
  command: ping -c 1 1.1.1.1
  register: ping
  changed_when: false
  ignore_errors: true

- name: set up the pc wifi connection
  when:
    - inventory_hostname == "pc"
    - ping.failed
  include_tasks: wifi.yml

- name: check if firewall is enabled
  become: true
  command: ufw status
  register: firewall

- name: set up the firewall
  when: "'Status: inactive' in firewall.stdout"
  include_tasks: firewall.yml

- name: create the user ssh key
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: true
    ssh_key_type: ed25519

- name: add a home server host entry for pc
  when: inventory_hostname == "pc"
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: ^.*\s{{ secrets.home_server.hostname }}$
    line: "{{ secrets.home_server.ip }} {{ secrets.home_server.hostname }}"

- name: add the pc user public ssh key to home server authorized keys
  when: inventory_hostname == "home_server"
  copy:
    src: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519.pub"
    dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"

- name: automatically accept new host keys in ssh connections
  lineinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    regexp: ^StrictHostKeyChecking
    line: StrictHostKeyChecking=accept-new
