---
- name: install desktop-related system packages
  become: true
  package:
    state: present
    name: "{{ packages.system }}"

- name: install flatpak desktop apps
  flatpak:
    method: user
    name: "{{ packages.flatpak }}"

- name: install catppuccin mocha cursors
  include_role:
    name: aur_pkg
  vars:
    package_name: catppuccin-cursors-mocha
    package_url: "https://aur.archlinux.org/catppuccin-cursors-mocha.git"

- name: enable sddm autologin
  become: true
  blockinfile:
    create: true
    path: /etc/sddm.conf.d/kde_settings.conf
    block: |
      [Autologin]
      Relogin=false
      Session=plasmax11
      User={{ ansible_env.USER }}

- name: enable sddm
  become: true
  systemd:
    enabled: true
    name: sddm
