---
- name: set up config files
  loop:
    - { src: gitconfig.j2, dest: .gitconfig }
    - { src: ssh-config.j2, dest: .ssh/config }
  template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"

- name: create ~/.config directory for both users
  loop:
    - { path: /root,                    become: true }
    - { path: "{{ ansible_env.HOME }}", become: false }
  become: "{{ item.become }}"
  file:
    state: directory
    path: "{{ item.path }}/.config"

- name: set up zsh for both users
  loop:
    - { user: root,                     home: /root,                    become: true }
    - { user: "{{ ansible_env.USER }}", home: "{{ ansible_env.HOME }}", become: false }
  include_tasks: zsh.yml
  args:
    apply:
      become: "{{ item.become }}"

- name: set up nvim
  include_tasks: nvim.yml

- name: set up vdirsyncer
  include_tasks: vdirsyncer.yml

- name: add user to the docker group
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: true

- name: enable sddm autologin
  become: true
  blockinfile:
    create: true
    path: /etc/sddm.conf.d/kde_settings.conf
    block: |
      [Autologin]
      Relogin=false
      Session=plasmax11
      User={{ ansible_env.USER }}
