---
- name: add dav password to the python keyring
  shell: |
    python - << EOF
    import keyring
    password = keyring.get_password('vdirsyncer', "{{ secrets.dav.username }}")
    if password != "{{ secrets.dav.password }}":
      keyring.set_password('vdirsyncer', "{{ secrets.dav.username }}", "{{ secrets.dav.password }}")
      print('password updated')
    EOF
  register: dav_password
  changed_when: "'password updated' in dav_password.stdout"

- name: create vdirsyncer collection directories
  loop:
    - "{{ ansible_env.HOME }}/.vdirsyncer/calendars/default"
    - "{{ ansible_env.HOME }}/.vdirsyncer/addressbooks/default"
  file:
    state: directory
    path: "{{ item }}"
