---
- name: create the ~/{{ item.dest }} directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/{{ item.dest }}"

- name: copy ~/{{ item.dest }} contents from the home server
  synchronize:
    src: "{{ home_server.user }}@{{ home_server.hostname }}:syncthing/{{ item.src }}/"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}/"

- name: check if ~/{{ item.dest }}/stignore.txt exists
  stat:
    path: "{{ ansible_env.HOME }}/{{ item.dest }}/stignore.txt"
  register: stignore

- name: include stignore.txt in .stignore for ~/{{ item.dest }}
  when: stignore.stat.exists
  lineinfile:
    create: true
    path: "{{ ansible_env.HOME }}/{{ item.dest }}/.stignore"
    line: "#include stignore.txt"
