---
- name: install arch script dependencies
  become: true
  package:
    state: present
    name:
      - dosfstools
      - arch-install-scripts

- name: set up the iac repositories
  loop:
    - arch
    - iac
  include_role:
    name: git_repository_setup
  vars:
    repository: "{{ item }}"
