---
- name: clone/update {{ secrets.git.remotes.origin }}/{{ repository }}
  git:
    repo: "{{ secrets.git.remotes.origin }}/{{ repository }}"
    dest: "{{ ansible_env.HOME }}/git/{{ repository }}"
  ignore_errors: true
  register: origin_pull

- name: set the backup remote for {{ repository }} repo
  when: origin_pull is succeeded
  args:
    chdir: "{{ ansible_env.HOME }}/git/{{ repository }}"
  shell: |
    if [ "$(git remote get-url backup)" != "{{ secrets.git.remotes.backup }}/{{ repository }}" ]; then
      git remote remove backup
      git remote add backup "{{ secrets.git.remotes.backup }}/{{ repository }}"
    else
      echo "remote properly configured"
    fi
  register: backup_setup
  changed_when: backup_setup.stdout == ""

- name: push to {{ secrets.git.remotes.backup }}/{{ repository }}
  when: origin_pull is succeeded
  command: git push backup
  args:
    chdir: "{{ ansible_env.HOME }}/git/{{ repository }}"
  register: git_push
  changed_when: secrets.git.remotes.backup.split('@')[1] in git_push.stderr

- name: clone/update {{ secrets.git.remotes.backup }}/{{ repository }}
  when: origin_pull is failed
  git:
    repo: "{{ secrets.git.remotes.backup }}/{{ repository }}"
    dest: "{{ ansible_env.HOME }}/git/{{ repository }}"
