---
- name: install sync tools
  become: true
  package:
    state: present
    name:
    - syncthing
    - rsync

- name: install rsync on the home server
  delegate_to: home_server
  become: true
  package:
    state: present
    name: rsync

- name: set up syncthing directories
  loop: "{{ syncthing_directories }}"
  include_tasks: syncthing_dir.yml

- name: allow syncthing traffic in ufw
  become: true
  ufw:
    rule: allow
    name: syncthing

- name: enable syncthing
  become: true
  systemd:
    enabled: true
    name: "syncthing@{{ ansible_env.USER }}"
