---
- name: check if the windows grub entry is present
  stat:
    path: /etc/grub.d/09_windows
  register: windows_grub

- name: check if windows is installed
  stat:
    path: /boot/EFI/Microsoft/Boot/bootmgfw.efi
  register: windows_efi

- name: set up dual boot
  when: not windows_grub.stat.exists and windows_efi.stat.exists
  become: true
  block:
  - name: get boot partition uuid
    shell: |
      set -o pipefail
      blkid | grep vfat | cut --delimiter=' ' --fields=2 | cut --delimiter='"' --fields=2
    register: boot_uuid
    changed_when: false

  - name: add a grub entry for windows
    template:
      src: windows-grub.j2
      dest: /etc/grub.d/09_windows
      mode: 0744

  - name: change grub timeout
    lineinfile:
      path: /etc/default/grub
      regexp: "^{{ item.key }}="
      line: "{{ item.key }}={{ item.value }}"
      state: present
    loop:
      - { key: "GRUB_TIMEOUT", value: "10" }
      - { key: "GRUB_DEFAULT", value: "1" }

  - name: update grub config
    command: grub-mkconfig -o /boot/grub/grub.cfg
