---
- name: allow kdeconnect traffic in ufw
  become: true
  loop:
    - tcp
    - udp
  ufw:
    rule: allow
    port: 1714:1764
    proto: "{{ item }}"
    comment: "kde connect"

- name: allow syncthing traffic in ufw
  become: true
  ufw:
    rule: allow
    name: syncthing

- name: reload ufw to apply changes
  become: true
  ufw:
    state: reloaded
  changed_when: false

- name: configure the vdirsyncer timer service
  become: true
  loop:
    - { var: "OnBootSec", value: '1m' }
    - { var: "OnUnitActiveSec", value: '5m' }
    - { var: "AccuracySec", value: '1m' }
  lineinfile:
    path: "/usr/lib/systemd/user/vdirsyncer.timer"
    regexp: "{{ item.var }}="
    line: "{{ item.var }}={{ item.value }}"
  register: vdirsyncer_timer_config

- name: enable systemd system services
  become: true
  loop: "{{ services.system }}"
  systemd:
    state: started
    enabled: true
    name: "{{ item }}"

- name: enable systemd user services
  loop: "{{ services.user }}"
  systemd:
    scope: user
    state: "{{ 'restarted' if item == 'vdirsyncer.timer' and vdirsyncer_timer_config.changed else 'started' }}"
    enabled: true
    name: "{{ item }}"
