---
- name: install devel packages
  become: true
  package:
    state: present
    name:
      - gcc
      - make
      - fakeroot
      - debugedit

- name: set makepkg config to use doas for privilege escalation
  lineinfile:
    create: true
    path: "{{ ansible_env.HOME }}/.makepkg.conf"
    regex: ^PACMAN_AUTH=.*$
    line: "PACMAN_AUTH=('doas')"
